name: Generate Sentinel Report

on:
  repository_dispatch:
    types: generate-sentinel-report

jobs:
  set-runner-os:
    name: Set Runner OS
    runs-on: ubuntu-latest
    outputs:
      platform:
        description: 'The OS to run the tests in'
        required: true
    steps:
      - name: Set Test Platform
        uses: codebytere/set-test-platform@v1

  build-and-test:
    name: Build Project
    needs: set-runner-os
    runs-on: ${{ inputs.platform }}
    inputs:
      platform:
        description: 'The OS to run the tests in'
        required: true
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Update Electron Version
        uses: codebytere/update-electron-version@v1

      - name: Install Dependencies
        run: npm ci

      - name: Run Test Suite
        run: npm run generate-test-report

      - name: Upload Test Report
        uses: actions/upload-artifact@v1
        with:
          name: report
          path: report.json

  send-data:
    name: Generate Report
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Download Report
        uses: actions/download-artifact@v1
        with:
          name: report

      - name: Send Data to Sentinel
        uses: codebytere/sentinel-client@v1

